backend:
  name: git-gateway
  branch: feat/netlify-cms
local_backend: true
publish_mode: editorial_workflow

media_folder: /uploads

collections:
  - name: 'blog'
    label: 'Artigos'
    folder: 'posts'
    create: true
    delete: true
    slug: '{{slug}}'

    fields:
      - { label: 'Título', name: 'title', widget: 'string', required: true }
      - { label: 'Autor', name: 'author', widget: 'string', required: true }
      - {
          label: 'Categoria',
          name: 'category',
          collection: 'categories',
          widget: 'relation',
          required: true,
          searchFields: 'title',
          valueField: 'title',
          displayFields: ['title'],
        }
      - {
          label: 'Data de Publicação',
          name: 'publishDate',
          widget: 'datetime',
          required: true,
        }
      - { label: 'Imagem', name: 'image', widget: 'image', required: true }
      - {
          label: 'Artigo em destaque?',
          name: 'featured',
          widget: 'boolean',
          required: true,
        }
      - {
          label: 'Artigo aparece no slider?',
          name: 'highlighted',
          widget: 'boolean',
        }
      - { label: 'Corpo', name: 'body', widget: 'markdown' }

  - name: 'categories'
    label: 'Categorias'
    identifier_field: slug
    folder: 'categories'
    slug: '{{slug}}'
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    delete: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string', required: true }
